# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - master
      - homolog
  pull_request:
    branches:
      - master
      - homolog

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: back-end/package-lock.json
      - uses: actions/checkout@v2
      - name: Running tests
        run: docker-compose -f docker-compose.test.yml --env-file=.env.test run --rm test